### PR TITLE
Feature: Disabling looping (formerly circular: false?) #219

### PR DESCRIPTION
**Pull request by ppmazur**
Add additional 'loop' flag to the defaults that allows to disable the loop effect.
Disable left arrow if user on the first slide.
Disable right arrow if user on the last slide.

Resolves: #219

### CODE REVIEW

**Comment by jedrzejchalubek** [comment]
Great 👏 Added some review [comments](https://github.com/glidejs/glide/pull/223/files) for you :)

**Comment by ppmazur** [comment]
Thanks for your comments Jedrzej :) I've updated the code accordingly.

**Comment by dodozhang21** [comment]
Can this be merged? I really need this feature.

**Comment by dodozhang21** [comment]
@ppmazur Hi I added a few comments, could you possibly address those in your PR? That's the only piece missing before I can make it work for my work.

**Comment by jedrzejchalubek** [comment]
Thanks, merged! 

Unfortunately, after testing, the disable class handling was a little bit cranky (it was adding disable class to navigations and was strictly limited to particular HTML structure), I only merged changes related only to new `rewind` option.

Disable class handling require to refactor and introduce breaking changes in controls component, so it has to go to next major release :(

**Comment by dodozhang21** [comment]
@jedrzejchalubek Is there a way I can use this now yet?

**Comment by jedrzejchalubek** [comment]
@dodozhang21 It was not released yet, so you have to use GitHub repo address and a specific hash of recent commit.

**Comment by lukeisif** [comment]
Was there any progress on it this at all?

**Pull request merged**
