### PR TITLE
Export throttle function from distributed modular entry

### PR DESCRIPTION
**Pull request by karolisgrinkevicius-home24**
# Description
Export throttle function within modular entry.

## Problem
In order to add extra throttled event listeners using this library you have to implement it on your own or use additional library for handling it which leads to increased bundle size since you're bundling `throttle` twice. 

Since `glidejs` library has this implementation within source code it does make sense to export it from modular ES entry for further usage.

### CODE REVIEW

**Comment by jedrzejchalubek** [comment]
A useful idea. However, The `throttle` function should not be passed to COMPONENTS object as it is not a component. Glide should not try to load it internally.

Let's make a separate export in entry files

**Comment by karolisgrinkevicius-home24** [comment]
@jedrzejchalubek Just to clarify by meaning the separate export in entry files what exactly files are you referring to?

**Comment by jedrzejchalubek** [comment]
These located in entry/ directory :smile:

**Comment by karolisgrinkevicius-home24** [comment]
@jedrzejchalubek As of this PR changes throttle export is not the part of Component as you mentioned. Maybe you meant something different?

**Comment by jedrzejchalubek** [comment]
Oh! Sorry. Don't know how, but I was thinking that it was added to the `COMPONENTS` variable 😅

Everything is good. However, can we remove compiled files in `dist/` folder from the PR?

**Comment by karolisgrinkevicius-home24** [comment]
@jedrzejchalubek thanks for your quick feedback. I can see the files in `dist` folder have only whitespace characters changed I'm pretty sure you might want to merge it anyway. The question is about `dist/glide.modular.esm.js`, shouldn't this be amended as well to have a throttle function build within?

**Comment by jedrzejchalubek** [comment]
Destination files are being built before release and tagging a new version. PR itself should not push compiled files as this makes conflicts in other PRs :)

**Comment by karolisgrinkevicius-home24** [comment]
Fair concern @jedrzejchalubek. Thanks. I've reverted ./dist in commit adce8100d8c2d509d56890fafc9febbf537bed97.

**Comment by jedrzejchalubek** [comment]
Great! Thanks!

**Pull request merged**
