### PR TITLE
Small improvements

### PR DESCRIPTION
**Pull request by omares**
* Fixes 'Uncaught TypeError: Cannot read property 'classList' of undefined"' when the element is not available
* Implements #307

@jedrzejchalubek Please review :)

### CODE REVIEW

**Comment by webunderconstruction** [comment]
Nice work @omares, any idea when it will be merged in?

**Comment by jedrzejchalubek** [comment]
@webunderconstruction I will get into this PR right after we merge #327. Both of these features will be released with v3.4.0 :)

**Comment by jedrzejchalubek** [comment]
Great 💯Thanks!

**Comment by marcosmyara** [comment]
Hi @omares i'm pretty sure @jedrzejchalubek didnt commit these changes in the new version of the script. I made the changes to "controls.js" like you suggested, but now i'm supposed to rebuild the glide.js bundle again, apparently using webpack or something. I had no idea what that was until i did some research but still i am completely lost in regards to using it (i'm a long way from having a good understanding of programming). could you please provide me a version of the script already updated so the control arrows (enable/disable) work as they're expected to, or maybe guide me in the right direction? thank you.

**Comment by omares** [comment]
My branch contains the updated distribution files. You can find them here https://github.com/omares/glide/tree/consolidated/dist 
Please keep in mind the branch is outdated and does not contain changes that have been applied upstream

Also generating the compiled files is fairly easy. Running `npm install` and then `npm run build` should do the trick. Assuming you have npm/node installed.

**Pull request merged**
