### PR TITLE
add "exports" to package.json

### PR DESCRIPTION
**Pull request by schiller-manuel**
this fixes ESM import

fixes https://github.com/TanStack/router/issues/2802

### CODE REVIEW

**Comment by rodrigopedra** [comment]
Hey @jedrzejchalubek, thanks for working on Glide.

This change broke my modular import:

```js
import Glide, {Images, Swipe} from '@glidejs/glide/dist/glide.modular.esm';
```

With the error message below:

```
Module not found: Error: Package path ./dist/glide.modular.esm.js is not exported from package /home/rodrigo/code/project/node_modules/@glidejs/glide (see exports field in /home/rodrigo/code/project/node_modules/@glidejs/glide/package.json)
```

Reverting to 3.6.2 resolved the issue.

How should I import it on the new version?

Also, I guess it is related, all SCSS imports stopped working:

```
ERROR in ./resources/sass/app.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Can't find stylesheet to import.
   ╷
20 │ @import '@glidejs/glide/src/assets/sass/glide.core.scss';
   │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
```

Reverting to 3.6.2 also resolved this.

**Comment by dzakki** [comment]
> Hey @jedrzejchalubek, thanks for working on Glide.
> 
> This change broke my modular import:
> 
> ```js
> import Glide, {Images, Swipe} from '@glidejs/glide/dist/glide.modular.esm';
> ```
> 
> With the error message below:
> 
> ```
> Module not found: Error: Package path ./dist/glide.modular.esm.js is not exported from package /home/rodrigo/code/project/node_modules/@glidejs/glide (see exports field in /home/rodrigo/code/project/node_modules/@glidejs/glide/package.json)
> ```
> 
> Reverting to 3.6.2 resolved the issue.
> 
> How should I import it on the new version?
> 
> Also, I guess it is related, all SCSS imports stopped working:
> 
> ```
> ERROR in ./resources/sass/app.scss
> Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
> ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
> Can't find stylesheet to import.
>    ╷
> 20 │ @import '@glidejs/glide/src/assets/sass/glide.core.scss';
>    │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>    ╵
> ```
> 
> Reverting to 3.6.2 also resolved this.

I'm facing the same issue 😢

**Comment by emrysal** [comment]
Similarly this looks to have broken on the @calcom project:

image

**Comment by jedrzejchalubek** [comment]
@rodrigopedra @dzakki Can you check if import simply as this will work fo you.

```
import Glide, {Images, Swipe} from '@glidejs/glide';
```

This should be all what is needed when project has `type: module`

**Comment by rodrigopedra** [comment]
Unfortunately, I can't add `"type": "module"` to my project's `package.json`, as it uses an outdated webpack configuration.

Tried adding it, but couldn't run.

An upgrade to this project is planned for the following months, so for now, I will just keep glide fixed at 3.6.2.

Thanks for looking into it @jedrzejchalubek, and thanks for this great project

**Pull request merged**
